config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :items

  validates :nickname,      presence: true
  validates :date_of_birth, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'is invalid. Input full-width characters' } do
    validates :given_name
    validates :family_name
  end

  with_options presence: true, format: { with: /\A[\p{katakana}ー－&&[^ -~｡-ﾟ]]+\z/, message: 'is invalid. Input full-width katakana characters' } do
    validates :given_name_kana
    validates :family_name_kana
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(
            :sign_up,
            keys: [
                :nickname,
                :family_name,
                :given_name,
                :family_name_kana,
                :given_name_kana,
                :date_of_birth
            ]
        )
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :select_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :redirect_to_show, only: [:edit, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      return redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      return redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    if @item.destroy
      return redirect_to root_path
    else
      render 'show'
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :price
    ).merge(user_id: current_user.id)
  end

  def select_item
    @item = Item.find(params[:id])
  end

  def redirect_to_show
    return redirect_to root_path if current_user.id != @item.user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

      <% render 'shared/error_messages', model: f.object %>

      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :hoge, id:"item-image" %>
        </div>
      </div>

      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-sales-status"}) %>
        </div>
      </div>

      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-prefecture"}) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        </div>
      </div>

      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
            </span>
          </div>
        </div>
      </div>

      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>

      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%= link_to 'もどる', item_path(f.object), class:"back-btn" %>
      </div>
    </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>

  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>

  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>

    <ul class='item-lists'>
      <% @items.each do |item|%>
        <li class='list'>
          <%= link_to item_path(item) do %>
            <div class='item-img-content'>
              <%= image_tag "item-sample.png", class: "item-img" %>

              <%# 商品が売れていればsold outと表示しましょう。 %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
              <%# /商品が売れていればsold outと表示しましょう。 %>

            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br><%= '配送料負担' %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

      <% render 'shared/error_messages', model: f.object %>

      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :hoge, id:"item-image" %>
        </div>
      </div>

      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-category"}) %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-sales-status"}) %>
        </div>
      </div>

      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-prefecture"}) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        </div>
      </div>

      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
            </span>
          </div>
        </div>
      </div>

      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>

      <div class="sell-btn-contents">
        <%= f.submit "出品する" ,class:"sell-btn" %>
        <%= link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag "item-sample.png" ,class:"item-box-img" %>

      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <%# //商品が売れている場合は、sold outを表示しましょう %>

    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @item.price %>
      </span>
      <span class="item-postage">
        <%= "配送料負担" %>
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で表示を変えましょう %>
    <%= link_to "商品の編集", edit_item_path, method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", item_path, method: :delete, class:"item-destroy" %>

    <%# 商品が売れていない場合はこちらを表示しましょう %>
    <%= link_to "購入画面に進む", "#" ,class:"item-red-btn"%>
    <%# /商品が売れていない場合はこちらを表示しましょう %>
    <%# /ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= "商品説明" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= "出品者名" %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= "カテゴリー名" %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= "商品の状態" %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= "発送料の負担" %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= "発送元の地域" %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= "発送日の目安" %></td>
        </tr>
      </tbody>
    </table>

    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>

  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
  <%# /詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Furima</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>

  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>